Repository goorm-highfive/xab, pull requests merged in 2025-01, with the labels that each got.

#42 feat: 로그인 페이지와 회원가입 페이지 UI 구현
  app/login/page.tsx
  app/sign-up/page.tsx
  src/assets/svgs/google-icon.svg
  src/assets/svgs/kakao-icon.svg
  src/assets/svgs/naver-icon.svg
  src/components/common/custom-form-field.tsx
  src/components/common/social-login-button.tsx
  src/components/login/login-form.tsx
  src/components/login/social-login.tsx
  src/components/password-and-security/password-form-field.tsx
  src/components/password-and-security/password-form.tsx
  src/components/sign-up/sign-up-form.tsx
  src/schema/user.ts
  tailwind.config.ts
Labels: Feature, Design

#41 feat: supabase DB 테이블 생성 및 연결 확인 테스트 코드 작성
  app/api/test-supabase/route.ts
  app/test-supabase/page.tsx
  package.json
  pnpm-lock.yaml
  src/middleware.ts
  src/types/.gitkeep
  src/utils/supabase.ts
  tsconfig.json
Labels: Feature

#43 feat: 게시글 뷰 페이지 UI 추가 및 기능 구현
  app/home/page.tsx
  app/post-detail/page.tsx
  app/profile/page.tsx
  app/settings/personal-information/page.tsx
  app/survey-detail/page.tsx
  pnpm-lock.yaml
  src/components/common/custom-alert-dialog.tsx
  src/components/common/survey-card.tsx
  src/components/post-action-bar.tsx
  src/components/post-article.tsx
  src/components/post-comment-input.tsx
  src/components/post-comment.tsx
  src/components/profile-edit/profile-edit-layout.tsx
  src/components/profile-edit/profile-info.tsx
  src/components/survey-detail/survey-comment-input.tsx
  src/components/survey-detail/survey-comment.tsx
  src/types/comment.ts
  src/types/survey.ts
  src/utils/like-formatters.ts
Labels: Feature, Design

#47 feat: Supabase 활용하여 로그인/회원가입 기능 구현 및 supabase와 연동
  app/api/test-supabase/route.ts
  app/auth/auth-error/page.tsx
  app/auth/callback/route.ts
  middleware.ts
  package.json
  pnpm-lock.yaml
  src/assets/svgs/default-profile.svg
  src/assets/svgs/naver-icon.svg
  src/components/common/site-header.tsx
  src/components/common/social-login-button.tsx
  src/components/login/login-form.tsx
  src/components/login/social-login.tsx
  src/components/profile-edit/profile-info.tsx
  src/components/setting/setting-menu.tsx
  src/components/setting/setting-profile-card.tsx
  src/components/sign-up/sign-up-form.tsx
  src/components/survey-detail/survey-comment-input.tsx
  src/components/survey-detail/survey-comment.tsx
  src/utils/logout.ts
  src/utils/supabase.ts
  src/utils/supabase/client.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
  tailwind.config.ts
Labels: Feature

#54 feat: 이메일 컨펌 및 유저 세션 감시 기능 구현
  app/account/check-email/page.tsx
  app/account/forgot-password/page.tsx
  app/account/login/page.tsx
  app/account/reset-password/page.tsx
  app/account/sign-up/page.tsx
  app/home/page.tsx
  app/layout.tsx
  app/login/page.tsx
  app/sign-up/page.tsx
  package.json
  src/components/account/account-layout.tsx
  src/components/account/check-email/check-email-client.tsx
  src/components/account/forgot-password/forgot-password-form.tsx
  src/components/account/login/login-form.tsx
  src/components/account/reset-password/reset-password-form.tsx
  src/components/account/sign-up/sign-up-form.tsx
  src/components/account/social-login-button.tsx
  src/components/account/social-login.tsx
  src/components/auth/client-session-manager.tsx
  src/components/common/custom-form-field.tsx
  src/components/common/modal-alert.tsx
  src/components/common/site-header.tsx
  src/components/password-and-security/password-form.tsx
  src/schema/user.ts
  src/types/supabase.ts
  src/utils/supabase/client.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: Feature, Refactor

#58 feat: 실시간 알림 기능 구현
  app/notify/page.tsx
  app/settings/page.tsx
  app/settings/personal-information/page.tsx
  package.json
  pnpm-lock.yaml
  src/components/auth/client-session-manager.tsx
  src/components/common/notification-button.tsx
  src/components/notify/notify-group.tsx
  src/components/notify/notify-item.tsx
  src/components/password-and-security/password-form.tsx
  src/hooks/.gitkeep
  src/hooks/useNotify.ts
  src/stores/.gitkeep
  src/stores/notify-store.ts
  src/types/.gitkeep
  src/types/supabase.ts
  src/utils/logout.ts
Labels: Feature

#60 feat: 게시글 추가 기능 구현
  app/@modal/(.)write/page.tsx
  app/write/page.tsx
  src/schema/write.ts
  src/types/supabase.ts
Labels: Feature

#74 feat: detail page 댓글 및 상호작용 추가
  app/api/comment-like/route.ts
  app/api/comments/route.ts
  app/api/survey-detail/[id]/route.ts
  app/home/page.tsx
  app/survey-detail/[id]/page.tsx
  src/components/common/site-header.tsx
  src/components/common/survey-card.tsx
  src/components/survey-detail/reply-input.tsx
  src/components/survey-detail/survey-comment-input.tsx
  src/components/survey-detail/survey-comment.tsx
  src/utils/toggleLikeAPI.ts
  src/utils/voteSubmitAPI.ts
Labels: Feature

#79 fix: 프로필 이미지 변경 관련 오류 해결
  src/components/common/survey-card.tsx
  src/components/home/profile-section.tsx
  src/components/home/suggest-section.tsx
  src/components/profile-edit/profile-info.tsx
  src/components/profile/profile-header.tsx
  src/components/setting/setting-profile-card.tsx
Labels: bug

#77 fix: Detail Page API 및 기타 오류 해결
  app/api/.gitkeep
  app/api/comments/route.ts
  app/api/survey-detail/[id]/route.ts
  app/api/test-supabase/route.ts
  app/settings/about/page.tsx
  app/settings/terms/page.tsx
  app/survey-detail/[id]/page.tsx
  app/test-supabase/page.tsx
  app/write/page.tsx
  src/components/account/check-email/check-email-client.tsx
  src/components/common/site-header.tsx
  src/components/common/survey-card.tsx
  src/components/survey-detail/reply-input.tsx
  src/components/survey-detail/survey-comment-input.tsx
  src/components/survey-detail/survey-comment.tsx
  src/schema/write.ts
  src/types/mockdata.ts
  src/types/supabase-types.ts
Labels: bug

#87 fix: email confirm 관련 파일 추가
  app/auth/confirm/route.ts
Labels: bug

#94 fix: 댓글 수정 및 삭제 권한 오류 픽스
  app/survey-detail/[id]/page.tsx
Labels: bug

#95 fix: 팔로잉, 팔로워 조회 오류 수정
  app/api/profile/[id]/followers/route.ts
  app/api/profile/[id]/followings/route.ts
  src/components/home/profile-section.tsx
  src/components/profile/profile-follow-list-skeleton.tsx
  src/components/profile/profile-user-follow-list.tsx
  src/components/profile/profile-user-list-modal.tsx
Labels: bug
